export const MODAL_OPEN = "MODAL_OPEN";

export const EMPLOYEE_SELECTED = "EMPLOYEE_SELECTED";

export const EMPLOYEE_FETCH_REQUESTED = "EMPLOYEE_FETCH_REQUESTED";
export const EMPLOYEE_FETCH_SUCCEEDED = "EMPLOYEE_FETCH_SUCCEEDED";
export const EMPLOYEE_FETCH_FAILED = "EMPLOYEE_FETCH_FAILED";

export const EMPLOYEE_ADD_REQUESTED = "EMPLOYEE_ADD_REQUESTED";
export const EMPLOYEE_ADD_SUCCEEDED = "EMPLOYEE_ADD_SUCCEEDED";
export const EMPLOYEE_ADD_FAILED = "EMPLOYEE_ADD_FAILED";

export const EMPLOYEE_UPDATE_REQUESTED = "EMPLOYEE_UPDATE_REQUESTED";
export const EMPLOYEE_UPDATE_SUCCEEDED = "EMPLOYEE_UPDATE_SUCCEEDED";
export const EMPLOYEE_UPDATE_FAILED = "EMPLOYEE_UPDATE_FAILED";

export const EMPLOYEE_DELETE_REQUESTED = "EMPLOYEE_DELETE_REQUESTED";
export const EMPLOYEE_DELETE_SUCCEEDED = "EMPLOYEE_DELETE_SUCCEEDED";
export const EMPLOYEE_DELETE_FAILED = "EMPLOYEE_DELETE_FAILED";

export const SAC_CONTENT_SELECTED = "SAC_CONTENT_SELECTED";

export const SAC_CONTENT_FETCH_REQUESTED = "SAC_CONTENT_FETCH_REQUESTED";
export const SAC_CONTENT_FETCH_SUCCEEDED = "SAC_CONTENT_FETCH_SUCCEEDED";
export const SAC_CONTENT_FETCH_FAILED = "SAC_CONTENT_FETCH_FAILED";

export const SAC_CONTENT_ADD_REQUESTED = "SAC_CONTENT_ADD_REQUESTED";
export const SAC_CONTENT_ADD_SUCCEEDED = "SAC_CONTENT_ADD_SUCCEEDED";
export const SAC_CONTENT_ADD_FAILED = "SAC_CONTENT_ADD_FAILED";

export const SAC_CONTENT_UPDATE_REQUESTED = "SAC_CONTENT_UPDATE_REQUESTED";
export const SAC_CONTENT_UPDATE_SUCCEEDED = "SAC_CONTENT_UPDATE_SUCCEEDED";
export const SAC_CONTENT_UPDATE_FAILED = "SAC_CONTENT_UPDATE_FAILED";

export const SAC_CONTENT_DELETE_REQUESTED = "SAC_CONTENT_DELETE_REQUESTED";
export const SAC_CONTENT_DELETE_SUCCEEDED = "SAC_CONTENT_DELETE_SUCCEEDED";
export const SAC_CONTENT_DELETE_FAILED = "SAC_CONTENT_DELETE_FAILED";